import { Referee } from './types';

export const MOCK_REFEREES: Referee[] = [
  {
    id: '1',
    fullName: 'Carlos Henrique',
    role: 'MAIN',
    phone: '81 98888-7777',
    city: 'Araçoiaba',
    state: 'PE',
    status: 'ACTIVE',
    gamesCount: 12,
    lastMatchDate: '2024-05-15',
    matchFee: 150,
  },
  {
    id: '2',
    fullName: 'João Batista',
    role: 'ASSISTANT',
    phone: '81 97777-6666',
    city: 'Paulista',
    state: 'PE',
    status: 'ACTIVE',
    gamesCount: 8,
    lastMatchDate: '2024-05-14',
    matchFee: 80,
  },
  {
    id: '3',
    fullName: 'Marcos Silva',
    role: 'ASSISTANT',
    phone: '81 96666-5555',
    city: 'Igarassu',
    state: 'PE',
    status: 'ACTIVE',
    gamesCount: 15,
    lastMatchDate: '2024-05-15',
    matchFee: 80,
  },
  {
    id: '4',
    fullName: 'Rafael Lima',
    role: 'SCORER',
    phone: '81 95555-4444',
    city: 'Abreu e Lima',
    state: 'PE',
    status: 'ACTIVE',
    gamesCount: 20,
    lastMatchDate: '2024-05-10',
    matchFee: 50,
  },
];
